#!/bin/sh /etc/rc.common

START=20
start()
{
	routerid=$(cat /etc/config/date.txt)
    # 判断frpc配置文件是否存在
if [ ! -f /etc/config/frpc ]; then
wget -c -4 -T 10 -P /etc/config https://zjzwxw.com/bak/frpc
fi

#判断rtty配置文件是否存在
if [ ! -f /etc/config/rtty ]; then
wget -c -4 -T 10 -P /etc/config https://zjzwxw.combak/rtty
fi
	uci -q batch <<-EOF >/dev/null
			set rtty.@rtty[0].id="$routerid"
			set rtty.@rtty[0].description="$routerid"
			commit rtty
			set frpc."$routerid"=conf
			set frpc."$routerid".type=http
			set frpc."$routerid".local_port=80
			set frpc."$routerid".subdomain="$routerid"
			commit frpc
		EOF
	fi
}